[package]
name = "mass-ip-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
clap = { version = "3.1.6", features = ["derive"] }

[dependencies.pnet]
version = "0.31.0"
